### PR TITLE
Feature/56 replace color

### PR DESCRIPTION
**Pull request by Iar0**
Solves #56 

- [x] replace functionality
- [x] UI with color picker
- [x] update README
- [x] commitzen log

### CODE REVIEW

**Comment by Iar0** [comment]
@SimoneFace add your findings here

**Comment by SimoneFace** [comment]
Thanks @Iar0 

OK current issues:

1. When I break out a colour and select the artboard, the screen centres on it perfectly. However, if I select any child of this artboard then the screen focuses I think on x=0 y=0 of the first artboard.

2. When I select the colorpicker and I am on a colour that is scrolled further down the window pane then the colorpicker does not scroll with me. Therefore I can't see it properly without scrolling away from the colour I was looking at. See pic:
Colorpicker not scrolling

3. There is no actual colorpicker? So when you move your mouse off the colormate window pane a colorpicker should appear. This way I can select a colour already on the canvas to replace a colour with. If I don't want to do that then I can go back to the window pane and enter a hex value or use the spectrum of colour. 

4. When I select a layer to change colour, then actually I replace the parent colour for all other layers that use this colour. However, as a designer I want to maybe just change "layer2"'s colour. So when I select a layer and replace colour it should just update this.

5. I selected a text layer in colormate and decided to change it's colour in the sketch colour panel instead. However after it's colour was updated there it was not reflected in colormate.

6. The "group" in the tree of layers shouldn't appear. So we want to have:
> artboard
>layer
Otherwise we get a lot of nesting and it's hard to decipher as a user. See pic:
Screenshot 2019-05-17 at 12 45 14

7. The selection tool works great but we probably need to make it clear in the colormate plugin that this is possible. So I will provide design for this. Likely to just be text in the loader or in the main window :)

**Comment by SimoneFace** [comment]
@Iar0 Let's discuss the above when you get the chance. A couple of these only should be the main priority for today :)

**Comment by SimoneFace** [comment]
@Iar0 

Another issue:
When using the colour picker, if I select a colour on the spectrum, the whole colour panel disappears and it replaces the colour. This is an issue because as a designer I need to play around in the spectrum of colours without it disappearing. SO I should see the item change colour, decide I don't like it and stay within the colour picker spectrum

**Comment by Raghav789** [comment]
eagerly awaiting for this merge

**Pull request merged**
